// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// qscl
Rcpp::List qscl(Rcpp::NumericVector p, const double M, const double k, double num_error_size, const bool lower, const bool log_p, const bool force);
RcppExport SEXP _sbim_qscl(SEXP pSEXP, SEXP MSEXP, SEXP kSEXP, SEXP num_error_sizeSEXP, SEXP lowerSEXP, SEXP log_pSEXP, SEXP forceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const double >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type num_error_size(num_error_sizeSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_p(log_pSEXP);
    Rcpp::traits::input_parameter< const bool >::type force(forceSEXP);
    rcpp_result_gen = Rcpp::wrap(qscl(p, M, k, num_error_size, lower, log_p, force));
    return rcpp_result_gen;
END_RCPP
}
// pscl
Rcpp::List pscl(Rcpp::NumericVector q, const double M, const double k, double num_error_size, const bool lower, const bool log_p, const bool force);
RcppExport SEXP _sbim_pscl(SEXP qSEXP, SEXP MSEXP, SEXP kSEXP, SEXP num_error_sizeSEXP, SEXP lowerSEXP, SEXP log_pSEXP, SEXP forceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const double >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type num_error_size(num_error_sizeSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_p(log_pSEXP);
    Rcpp::traits::input_parameter< const bool >::type force(forceSEXP);
    rcpp_result_gen = Rcpp::wrap(pscl(q, M, k, num_error_size, lower, log_p, force));
    return rcpp_result_gen;
END_RCPP
}
// rscl
Rcpp::NumericVector rscl(const int n, const double M, const double k);
RcppExport SEXP _sbim_rscl(SEXP nSEXP, SEXP MSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(rscl(n, M, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sbim_qscl", (DL_FUNC) &_sbim_qscl, 7},
    {"_sbim_pscl", (DL_FUNC) &_sbim_pscl, 7},
    {"_sbim_rscl", (DL_FUNC) &_sbim_rscl, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sbim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
