# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The SCL Distribution
#'
#' Quantile function, distribution function, and random generation for the SCL distribution. See Park and Won (2022) for information about the SCL distribution.
#'
#' @param p probability
#' @param M parameter to the SCL distribution
#' @param precision The requested level of precision for the outputs of qscl and pscl functions, as the number of decimal places. See Details for more information. (Details: precision can be any positive real, and checks if the standard error of the output is not greater than 10^{-precision}.)
#' @return b b
#' @examples
#' asdf5
#' @export
qscl <- function(p, M, precision, lower = TRUE, log = FALSE) {
    .Call(`_mclle_qscl`, p, M, precision, lower, log)
}

rscl <- function(n, M) {
    .Call(`_mclle_rscl`, n, M)
}

rscl2 <- function(n, M) {
    .Call(`_mclle_rscl2`, n, M)
}

